include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    file_names: false
